version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data: